Repository Q42/sanity-plugin-page-tree, pull requests merged in 2025-04, with the labels that each got.

#55 WIP Feature/presentation mode
  .gitignore
  package-lock.json
  package.json
  src/helpers/page-tree.ts
  src/index.ts
  src/presentation-mode.ts
  src/queries/index.ts
  src/types.ts
Labels: feature

#65 Release/v1.6.0
  package-lock.json
  package.json
  src/helpers/page-tree.test.ts
Labels: maintenance

#49 Fix showing page tree items without slug
  src/components/PageTreeViewItem.tsx
  src/helpers/page-tree.ts
Labels: bugfix
